### PR TITLE
Implemented features for advanced scheduling.

### PR DESCRIPTION
**Pull request by ibisek**
Hi there! Perhaps a year ago I've added some more functionality to your nice project which I've been successfully using on the AVR, STM32 and the ESP8266 platforms. Finally, I've come to a point I could use it with Arduino too, just need to import "my" header file every time while it would be more convenient to add it to your official library. 

Hence here comes my contribution. If you like it, please feel free to append it to your code :)

### CODE REVIEW

**Comment by joysfera** [comment]
That is a neat trick how to manage tasks without assigning them an ID, I like it. Unfortunately it's going to misbehave when someone creates several tasks calling identical function, like say the provided example called MultiBlink.
I feel like adding these extra functions would require an additional check in functions creating tasks that would prevent creating a task with an already used TaskCallback. However, as that would break the MultiBlink example and possibly also users' code, a conditional compilation of two different, incompatible versions would have to be added. It's getting complicated...

**Comment by ibisek** [comment]
All right, I see that now. I did not consider someone would be doing such a thing. Calling the the additional methods would then really need a knowledge of an schedule ID which complicates all the consequently added methods. And having two different Taskers would be just confusing.. :| So shall we  cancel this one?

**Comment by joysfera** [comment]
I'm not for cancelling it right away, the idea is great, the patch could be applied as-is - I'm just thinking about how to document it super clearly so that no user gets confused. Give me some time to think it through.

**Comment by joysfera** [comment]
OK, took me some time to think it through but I believe the just released Tasker v2.0 not only incorporates all features of your patch but also brings some quite nice improvements over it. So thanks for the idea and enjoy my implementation :-)

**Pull request closed without merging**
